# -*- coding: utf-8 -*-
"""扩充 CWE 知识库：补齐 strategy.py 支持但知识库缺失的漏洞类型。一次性脚本。"""
import json
from pathlib import Path

NEW = [
    {"id": "CWE-502", "cwe_id": "CWE-502", "title": "Insecure Deserialization",
     "summary": "Untrusted data is deserialized without validation, allowing object injection or remote code execution.",
     "owasp": ["A08:2021 Software and Data Integrity Failures"],
     "vuln_types": ["Insecure Deserialization", "Deserialization"],
     "aliases": ["deserialization", "unsafe deserialization", "反序列化", "对象注入"],
     "sources": ["request.data", "request.body", "cookie", "$_POST", "req.body"],
     "sinks": ["pickle.loads", "cPickle.loads", "yaml.load", "unserialize", "ObjectInputStream.readObject", "marshal.loads"],
     "sanitizers": ["yaml.safe_load", "json.loads", "allowlist of classes", "signature verification"],
     "verification_checks": ["Confirm untrusted input is passed to a deserialization sink.",
                             "Confirm the deserializer can instantiate arbitrary classes or call __reduce__.",
                             "Confirm no integrity check (HMAC/signature) protects the serialized blob."],
     "false_positive_signals": ["Only json.loads / yaml.safe_load is used on the untrusted data.",
                                "The serialized data is signed and verified before deserialization.",
                                "The input is a trusted, application-generated constant."],
     "dynamic_strategy": "harness",
     "remediation": ["Prefer safe formats (JSON) and safe loaders (yaml.safe_load).",
                     "Never deserialize untrusted data with pickle/unserialize/ObjectInputStream.",
                     "If unavoidable, sign+verify payloads and restrict allowed classes."],
     "references": ["https://cwe.mitre.org/data/definitions/502.html"],
     "tags": ["deserialization", "rce", "injection"]},
    {"id": "CWE-798", "cwe_id": "CWE-798", "title": "Hardcoded Secret",
     "summary": "Credentials or secret keys are embedded directly in source code, exposing them to anyone with code access.",
     "owasp": ["A07:2021 Identification and Authentication Failures", "A05:2021 Security Misconfiguration"],
     "vuln_types": ["Hardcoded Secret", "Hardcoded Credential"],
     "aliases": ["hardcoded password", "hardcoded credentials", "secret", "硬编码密钥", "硬编码凭证"],
     "sources": [], "sinks": ["password =", "api_key =", "secret =", "token =", "private_key ="],
     "sanitizers": ["environment variable", "secret manager", "vault"],
     "verification_checks": ["Confirm the literal is a real secret, not a placeholder or example.",
                             "Confirm the secret is reachable/used by runtime code.",
                             "Assess blast radius: which service/account the secret unlocks."],
     "false_positive_signals": ["The value is a placeholder (your-key, example, changeme, xxx).",
                                "The value is a test fixture never used in production.",
                                "It is a public/non-sensitive identifier."],
     "dynamic_strategy": "not_applicable",
     "remediation": ["Move secrets to environment variables or a secret manager.",
                     "Rotate any exposed credential immediately.",
                     "Add secret scanning (Gitleaks) to CI to prevent recurrence."],
     "references": ["https://cwe.mitre.org/data/definitions/798.html"],
     "tags": ["secret", "credential", "static"]},
    {"id": "CWE-94", "cwe_id": "CWE-94", "title": "Code Injection",
     "summary": "User-controlled input is executed as code via eval/exec-style sinks.",
     "owasp": ["A03:2021 Injection"], "vuln_types": ["Code Injection"],
     "aliases": ["code injection", "代码注入", "eval injection"],
     "sources": ["request.args", "request.form", "req.body", "$_GET", "input()"],
     "sinks": ["eval", "exec", "compile", "Function(", "new Function", "vm.runInThisContext"],
     "sanitizers": ["ast.literal_eval", "allowlist", "sandboxed evaluator"],
     "verification_checks": ["Confirm user input reaches eval/exec-style execution.",
                             "Confirm no safe evaluator (ast.literal_eval) or allowlist is used."],
     "false_positive_signals": ["ast.literal_eval is used instead of eval.",
                                "The evaluated expression is a fixed literal."],
     "dynamic_strategy": "harness",
     "remediation": ["Avoid eval/exec on user input.", "Use ast.literal_eval or a safe parser.",
                     "Validate against a strict allowlist."],
     "references": ["https://cwe.mitre.org/data/definitions/94.html"], "tags": ["code-injection", "rce", "injection"]},
    {"id": "CWE-1336", "cwe_id": "CWE-1336", "title": "Server-Side Template Injection",
     "summary": "User input is embedded into a server-side template that is then rendered, allowing expression evaluation or RCE.",
     "owasp": ["A03:2021 Injection"], "vuln_types": ["Server-Side Template Injection", "SSTI", "Template Injection"],
     "aliases": ["ssti", "template injection", "模板注入"],
     "sources": ["request.args", "request.form", "req.query", "$_GET"],
     "sinks": ["render_template_string", "Template(", "env.from_string", "Twig", "Handlebars.compile", ".render("],
     "sanitizers": ["sandboxed environment", "autoescape", "static template with context data"],
     "verification_checks": ["Confirm user input is concatenated into the template string itself (not just passed as data).",
                             "Confirm the engine evaluates expressions like {{7*7}}."],
     "false_positive_signals": ["User input is passed as template context data, not into the template source.",
                                "A sandboxed template environment is enforced."],
     "dynamic_strategy": "http_or_harness",
     "remediation": ["Never build templates from user input.", "Pass user data as context variables only.",
                     "Use a sandboxed template environment."],
     "references": ["https://cwe.mitre.org/data/definitions/1336.html"], "tags": ["ssti", "injection", "rce"]},
    {"id": "CWE-611", "cwe_id": "CWE-611", "title": "XML External Entity (XXE)",
     "summary": "An XML parser processes external entity references in untrusted XML, enabling file disclosure or SSRF.",
     "owasp": ["A05:2021 Security Misconfiguration"], "vuln_types": ["XXE", "XML External Entity"],
     "aliases": ["xxe", "xml external entity", "xml 外部实体"],
     "sources": ["request.data", "request.body", "uploaded xml"],
     "sinks": ["etree.parse", "lxml.etree", "DocumentBuilder", "SAXParser", "simplexml_load_string"],
     "sanitizers": ["resolve_entities=False", "disable DTD", "FEATURE_SECURE_PROCESSING"],
     "verification_checks": ["Confirm untrusted XML is parsed with external entity resolution enabled.",
                             "Confirm DTD/entity processing is not disabled."],
     "false_positive_signals": ["The parser disables DTDs / external entities.", "defusedxml or secure processing is used."],
     "dynamic_strategy": "http_or_harness",
     "remediation": ["Disable DTD and external entity resolution.", "Use defusedxml (Python) or secure parser config.",
                     "Do not accept raw XML where JSON suffices."],
     "references": ["https://cwe.mitre.org/data/definitions/611.html"], "tags": ["xxe", "xml", "ssrf"]},
    {"id": "CWE-434", "cwe_id": "CWE-434", "title": "Arbitrary File Upload",
     "summary": "An application allows uploading files that can be executed or interpreted by the server.",
     "owasp": ["A04:2021 Insecure Design"], "vuln_types": ["Arbitrary File Upload", "File Upload"],
     "aliases": ["file upload", "任意文件上传", "webshell upload"],
     "sources": ["request.files", "$_FILES", "multipart upload"],
     "sinks": ["save(", "move_uploaded_file", "write to webroot"],
     "sanitizers": ["extension allowlist", "content-type check", "store outside webroot", "random filename"],
     "verification_checks": ["Confirm uploaded filename/extension is user-controlled.",
                             "Confirm the file lands in an executable/served location.",
                             "Confirm no allowlist or content validation blocks dangerous types."],
     "false_positive_signals": ["Strict extension allowlist is enforced.",
                                "Files are stored outside the web root with random names."],
     "dynamic_strategy": "http",
     "remediation": ["Enforce an extension/content allowlist.", "Store uploads outside the web root, rename randomly.",
                     "Never execute uploaded content."],
     "references": ["https://cwe.mitre.org/data/definitions/434.html"], "tags": ["upload", "rce"]},
    {"id": "CWE-639", "cwe_id": "CWE-639", "title": "IDOR / Broken Access Control",
     "summary": "Authorization is not enforced on object references, letting a user access others' objects by changing an identifier.",
     "owasp": ["A01:2021 Broken Access Control"],
     "vuln_types": ["IDOR", "Broken Access Control", "Auth Bypass", "Mass Assignment"],
     "aliases": ["idor", "bola", "broken access control", "越权", "水平越权", "垂直越权"],
     "sources": ["request.args id", "path param id", "user_id", "account"],
     "sinks": ["db.get(id)", "find_by_id", "load object without owner check"],
     "sanitizers": ["ownership check", "role check", "policy enforcement"],
     "verification_checks": ["Confirm an object reference (ID) is user-controlled.",
                             "Confirm no ownership/authorization check ties the object to the current user."],
     "false_positive_signals": ["An ownership or role check is enforced before access.",
                                "The identifier is unguessable and access is additionally authorized."],
     "dynamic_strategy": "http",
     "remediation": ["Enforce per-object authorization (ownership/role) on every access.",
                     "Use indirect, unguessable references where feasible.",
                     "Apply deny-by-default access policies."],
     "references": ["https://cwe.mitre.org/data/definitions/639.html"], "tags": ["access-control", "idor", "authz"]},
    {"id": "CWE-601", "cwe_id": "CWE-601", "title": "Open Redirect",
     "summary": "User-controlled input is used as a redirect target, enabling phishing and token leakage.",
     "owasp": ["A01:2021 Broken Access Control"],
     "vuln_types": ["Open Redirect", "CRLF Injection", "Host Header Injection"],
     "aliases": ["open redirect", "url redirection", "开放重定向"],
     "sources": ["request.args url", "next", "return", "redirect param"],
     "sinks": ["redirect(", "Location header", "res.redirect", "header('Location')"],
     "sanitizers": ["allowlist of hosts", "relative path only", "url validation"],
     "verification_checks": ["Confirm the redirect target is user-controlled.",
                             "Confirm no allowlist restricts destinations to trusted hosts."],
     "false_positive_signals": ["Only relative paths are allowed.", "Destination is validated against a host allowlist."],
     "dynamic_strategy": "http",
     "remediation": ["Allowlist redirect destinations.", "Only permit relative paths or known hosts.",
                     "Avoid putting raw user input in Location headers."],
     "references": ["https://cwe.mitre.org/data/definitions/601.html"], "tags": ["redirect", "phishing"]},
    {"id": "CWE-943", "cwe_id": "CWE-943", "title": "NoSQL / LDAP / XPath Injection",
     "summary": "User input is used to build NoSQL/LDAP/XPath queries without proper neutralization.",
     "owasp": ["A03:2021 Injection"], "vuln_types": ["NoSQL Injection", "LDAP Injection", "XPath Injection"],
     "aliases": ["nosql injection", "ldap injection", "xpath injection", "注入"],
     "sources": ["request.json", "request.args", "req.body", "$_GET"],
     "sinks": ["collection.find", "$where", "ldap search filter", "xpath("],
     "sanitizers": ["query builder with binding", "input allowlist", "escaping"],
     "verification_checks": ["Confirm user input is concatenated into a NoSQL/LDAP/XPath query.",
                             "Confirm no parameter binding or escaping neutralizes it."],
     "false_positive_signals": ["Parameterized query builder is used.", "Input is strictly validated/escaped."],
     "dynamic_strategy": "http_or_harness",
     "remediation": ["Use parameterized query APIs.", "Escape/validate query metacharacters.",
                     "Apply least-privilege on the datastore."],
     "references": ["https://cwe.mitre.org/data/definitions/943.html"], "tags": ["injection", "nosql", "ldap", "xpath"]},
    {"id": "CWE-327", "cwe_id": "CWE-327", "title": "Weak Cryptography / Weak Hash",
     "summary": "Broken or risky cryptographic algorithms (MD5, SHA1, DES, ECB) are used for security-sensitive operations.",
     "owasp": ["A02:2021 Cryptographic Failures"],
     "vuln_types": ["Weak Cryptography", "Weak Hash", "Insecure Random"],
     "aliases": ["weak crypto", "weak hash", "md5", "sha1", "insecure random", "弱加密", "弱哈希"],
     "sources": [], "sinks": ["md5(", "sha1(", "DES", "RC4", "ECB", "random.random", "Math.random"],
     "sanitizers": ["sha256", "bcrypt", "argon2", "AES-GCM", "secrets module", "os.urandom"],
     "verification_checks": ["Confirm a weak algorithm is used for a security purpose (password, token, signature).",
                             "Confirm it is not used for a non-security checksum."],
     "false_positive_signals": ["The weak hash is used only for a non-security checksum/dedup.",
                                "A strong algorithm is actually used."],
     "dynamic_strategy": "not_applicable",
     "remediation": ["Use SHA-256+/bcrypt/argon2 for hashing; AES-GCM for encryption.",
                     "Use a CSPRNG (secrets/os.urandom) for security tokens.", "Remove DES/RC4/ECB usage."],
     "references": ["https://cwe.mitre.org/data/definitions/327.html"], "tags": ["crypto", "hash", "static"]},
    {"id": "CWE-1104", "cwe_id": "CWE-1104", "title": "Vulnerable/Outdated Dependency",
     "summary": "The project depends on components with known vulnerabilities (CVEs).",
     "owasp": ["A06:2021 Vulnerable and Outdated Components"],
     "vuln_types": ["Outdated Dependency", "CVE", "Sensitive Data Exposure"],
     "aliases": ["outdated dependency", "vulnerable component", "cve", "依赖漏洞"],
     "sources": [], "sinks": ["requirements.txt", "package.json", "pom.xml", "composer.json"],
     "sanitizers": ["pinned patched version", "SCA in CI"],
     "verification_checks": ["Confirm the vulnerable version is actually installed.",
                             "Assess whether the vulnerable code path is reachable in this project."],
     "false_positive_signals": ["The advisory does not affect the used feature/version.",
                                "A patched version is already pinned."],
     "dynamic_strategy": "not_applicable",
     "remediation": ["Upgrade to a patched version.", "Add SCA (Trivy/OSV) scanning to CI.",
                     "Remove unused vulnerable dependencies."],
     "references": ["https://cwe.mitre.org/data/definitions/1104.html"], "tags": ["sca", "dependency", "static"]},
    {"id": "CWE-16", "cwe_id": "CWE-16", "title": "Security Misconfiguration",
     "summary": "Insecure configuration such as debug mode enabled, missing security headers, or overly permissive settings.",
     "owasp": ["A05:2021 Security Misconfiguration"],
     "vuln_types": ["Insecure Configuration", "Debug Mode", "Missing Security Header", "CORS Misconfiguration"],
     "aliases": ["insecure configuration", "debug mode", "missing security header", "cors misconfiguration", "配置不当"],
     "sources": [], "sinks": ["debug=True", "Access-Control-Allow-Origin: *", "DEBUG = True", "app.run(debug=True)"],
     "sanitizers": ["debug disabled in prod", "strict CORS allowlist", "security headers set"],
     "verification_checks": ["Confirm the insecure setting is active in production configuration.",
                             "Assess exposure (info leak, cross-origin access)."],
     "false_positive_signals": ["The setting is guarded by an environment check and off in prod.",
                                "CORS is restricted to a trusted allowlist."],
     "dynamic_strategy": "not_applicable",
     "remediation": ["Disable debug in production.", "Set security headers (CSP, HSTS, X-Frame-Options).",
                     "Restrict CORS to trusted origins."],
     "references": ["https://cwe.mitre.org/data/definitions/16.html"], "tags": ["config", "headers", "cors", "static"]},
]


def main():
    path = Path(__file__).resolve().parent.parent / "backend" / "rag" / "sources" / "cwe_core.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    existing = {i["cwe_id"] for i in data["items"]}
    added = 0
    for item in NEW:
        item.setdefault("source_type", "cwe_core")
        if item["cwe_id"] not in existing:
            data["items"].append(item)
            added += 1
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"新增 {added} 条，知识库总数 {len(data['items'])}")
    print("覆盖 CWE:", [i["cwe_id"] for i in data["items"]])


if __name__ == "__main__":
    main()
